### ISSUE TITLE
No return on a variable that is undefined

### ISSUE THREAD

**Issue by bobsingor** [magynhard/curly-bracket-parser#1]
Thanks for building this library.

Whenever I have a variable that is undefined the library does not return anything. My application basically just freezes because it is waiting for a return. 

I think it would be better to change undefined variables to a empty string or to return an error that it is not allowed to have a undefined variable.

**Comment by magynhard** [comment]
@bobsingor thank you very much for your report.
I'm happy to hear, that more and more people use and like this library.

For me that is a bug that needs to be fixed. I will do an update soon!

**Comment by magynhard** [comment]
@bobsingor i just created a new release 1.1.7.

Here 'empty' values like null, NaN, Infinity or undefined are processed as empty string.

Does it work as you expected?

**Comment by bobsingor** [comment]
@magynhard This is perfect! Thanks!
