### ISSUE TITLE
Option to ignore unresolved variables error.

### ISSUE THREAD

**Issue by bobsingor** [magynhard/curly-bracket-parser#2]
Whenever I have a string with multiple variables and there is one variable that is unresolved I currently get this error:
"There are unresolved variables in the given string: {{variable}}"

I would like an option to ignore this error and return the string with all the variables that are resolved and the ones that are not resolved keep as is or return as empty string.

**Comment by magynhard** [comment]
Hi @bobsingor thank you for your question.

I guess your feature is already available, but I might think about to extend the default README with an example to make it more obvious, as it is a feature that is often needed.

Have a look at the jsdoc here:
https://github.com/magynhard/curly-bracket-parser/blob/master/doc/curly-bracket-parser.jsdoc.md#CurlyBracketParser.parse

In addition a shortcut `'empty'` for `options.unresolved_vars` might be helpful, using `replace` and setting the `options.replace_pattern` to an empty string implicitly.

**Comment by bobsingor** [comment]
@magynhard Thanks for your answer. The way it is, is perfect. I should have studied the documentation better!
